# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  # Enable container name DNS for non-default Podman networks.
  # https://github.com/NixOS/nixpkgs/issues/226365
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."memos" = {
    image = "docker.io/neosmemo/memos:stable";
    environment = {
      "PGID" = "1000";
      "PUID" = "99";
      "UMASK" = "022";
    };
    volumes = [
      "/home/haze/memos:/var/opt/memos:rw"
    ];
    ports = [
      "5230:5230/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=memos"
      "--network=haze-containernet"
    ];
  };
  systemd.services."podman-memos" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-haze-containernet.service"
    ];
    requires = [
      "podman-network-haze-containernet.service"
    ];
    partOf = [
      "podman-compose-stefan-root.target"
    ];
    wantedBy = [
      "podman-compose-stefan-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-haze-containernet" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f haze-containernet";
    };
    script = ''
      podman network inspect haze-containernet || podman network create haze-containernet
    '';
    partOf = [ "podman-compose-stefan-root.target" ];
    wantedBy = [ "podman-compose-stefan-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-stefan-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
